const images = [
  {
    id: 1,
    img: '../../images/apples-1.jpg',
    category: ['nature', 'fruits', 'apples', 'red', 'green'],
    mainCategory: 'fruits',
  },
  {
    id: 2,
    img: '../../images/apples-2.jpg',
    category: ['nature', 'fruits', 'apples', 'pink', 'green'],
    mainCategory: 'fruits',
  },
  {
    id: 3,
    img: '../../images/beetles.jpg',
    category: ['nature', 'insect', 'beetles', 'pink', 'green'],
    mainCategory: 'insect',
  },
  {
    id: 4,
    img: '../../images/bird-1.jpg',
    category: ['nature', 'birds', 'animal', 'yellow'],
    mainCategory: 'birds',
  },
  {
    id: 5,
    img: '../../images/bird-2.jpg',
    category: ['nature', 'birds', 'animal', 'yellow', 'pink'],
    mainCategory: 'birds',
  },
  {
    id: 6,
    img: '../../images/butterfly.jpg',
    category: ['nature', 'insect', 'animal', 'butterfly', 'red', 'green'],
    mainCategory: 'insect',
  },
  {
    id: 7,
    img: '../../images/cherry-1.jpg',
    category: ['nature', 'flowers', 'blossom', 'white', 'blue', 'insect'],
    mainCategory: 'flowers',
  },
  {
    id: 8,
    img: '../../images/cherry-2.jpg',
    category: ['nature', 'flowers', 'blossom', 'pink'],
    mainCategory: 'flowers',
  },
  {
    id: 9,
    img: '../../images/cherry-3.jpg',
    category: ['nature', 'flowers', 'blossom', 'pink'],
    mainCategory: 'flowers',
  },
  {
    id: 10,
    img: '../../images/currants.jpg',
    category: ['nature', 'fruits', 'red', 'green'],
    mainCategory: 'fruits',
  },
  {
    id: 11,
    img: '../../images/gemstone.jpg',
    category: ['nature', 'stones', 'gemstones', 'pink'],
    mainCategory: 'stones',
  },
  {
    id: 12,
    img: '../../images/insect-1.jpg',
    category: ['nature', 'insect', 'animal', 'green'],
    mainCategory: 'insect',
  },
  {
    id: 13,
    img: '../../images/insect-2.jpg',
    category: ['nature', 'insect', 'animal', 'pink'],
    mainCategory: 'insect',
  },
  {
    id: 14,
    img: '../../images/insect-3.jpg',
    category: ['nature', 'insect', 'animal', 'purple'],
    mainCategory: 'insect',
  },
  {
    id: 15,
    img: '../../images/kingfisher.jpg',
    category: ['nature', 'birds', 'animals', 'blue'],
    mainCategory: 'birds',
  },
  {
    id: 16,
    img: '../../images/ladybug.jpg',
    category: ['nature', 'insect', 'animal', 'ladybug', 'green'],
    mainCategory: 'insect',
  },
  {
    id: 17,
    img: '../../images/lavender.jpg',
    category: ['nature', 'flowers', 'blossom', 'purple'],
    mainCategory: 'flowers',
  },
  {
    id: 18,
    img: '../../images/lemon.jpg',
    category: ['nature', 'fruits', 'lemon', 'yellow', 'green'],
    mainCategory: 'fruits',
  },
  {
    id: 19,
    img: '../../images/oranges.jpg',
    category: ['nature', 'fruits', 'orange'],
    mainCategory: 'fruits',
  },
  {
    id: 20,
    img: '../../images/pebble.jpg',
    category: ['nature', 'stones', 'pebble', 'orange'],
    mainCategory: 'stones',
  },
  {
    id: 21,
    img: '../../images/pink.jpg',
    category: ['nature', 'flowers', 'blossom', 'pink'],
    mainCategory: 'flowers',
  },
  {
    id: 22,
    img: '../../images/pomegranate.jpg',
    category: ['nature', 'fruits', 'red'],
    mainCategory: 'fruits',
  },
  {
    id: 23,
    img: '../../images/poppies.jpg',
    category: ['nature', 'flowers', 'red', 'green'],
    mainCategory: 'flowers',
  },
  {
    id: 24,
    img: '../../images/spring.jpg',
    category: ['nature', 'flowers', 'pink', 'green'],
    mainCategory: 'flowers',
  },
  {
    id: 25,
    img: '../../images/stones-1.jpg',
    category: ['nature', 'stones', 'blue'],
    mainCategory: 'stones',
  },
  {
    id: 26,
    img: '../../images/stones-2.jpg',
    category: ['nature', 'stones', 'blue', 'red'],
    mainCategory: 'stones',
  },
  {
    id: 27,
    img: '../../images/flamengo.jpg',
    category: ['nature', 'birds', 'pink', 'animals'],
    mainCategory: 'birds',
  },
];
export default images;
